// GENERATED by scripts/build-scripture-seed.mjs. Do not edit by hand.
// Source: World English Bible (public domain), https://ebible.org/web/
import type { ScriptureRow } from '../types';

export const SCRIPTURE_SEED: ScriptureRow[] = [
  {
    "id": "web-1corinthians-10-13",
    "book": "1 Corinthians",
    "chapter": 10,
    "verse": 13,
    "text": "No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape, that you may be able to endure it.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "web-james-4-7",
    "book": "James",
    "chapter": 4,
    "verse": 7,
    "text": "Be subject therefore to God. Resist the devil, and he will flee from you.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "web-1peter-5-8",
    "book": "1 Peter",
    "chapter": 5,
    "verse": 8,
    "text": "Be sober and self-controlled. Be watchful. Your adversary, the devil, walks around like a roaring lion, seeking whom he may devour.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "vigilance"
  },
  {
    "id": "web-hebrews-4-15",
    "book": "Hebrews",
    "chapter": 4,
    "verse": 15,
    "text": "For we don’t have a high priest who can’t be touched with the feeling of our infirmities, but one who has been in all points tempted like we are, yet without sin.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "shame"
  },
  {
    "id": "web-galatians-5-1",
    "book": "Galatians",
    "chapter": 5,
    "verse": 1,
    "text": "Stand firm therefore in the liberty by which Christ has made us free, and don’t be entangled again with a yoke of bondage.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "freedom"
  },
  {
    "id": "web-proverbs-25-28",
    "book": "Proverbs",
    "chapter": 25,
    "verse": 28,
    "text": "Like a city that is broken down and without walls is a man whose spirit is without restraint.",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "web-titus-2-12",
    "book": "Titus",
    "chapter": 2,
    "verse": 12,
    "text": "instructing us to the intent that, denying ungodliness and worldly lusts, we would live soberly, righteously, and godly in this present age;",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "web-philippians-4-8",
    "book": "Philippians",
    "chapter": 4,
    "verse": 8,
    "text": "Finally, brothers, whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report: if there is any virtue and if there is any praise, think about these things.",
    "translation": "WEB",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "craving,mind"
  },
  {
    "id": "web-romans-12-2",
    "book": "Romans",
    "chapter": 12,
    "verse": 2,
    "text": "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.",
    "translation": "WEB",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "habit,mind"
  },
  {
    "id": "web-romans-8-1",
    "book": "Romans",
    "chapter": 8,
    "verse": 1,
    "text": "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit.",
    "translation": "WEB",
    "primary_emotion_tag": "shame",
    "secondary_tags": "guilt,relapse"
  },
  {
    "id": "web-hebrews-4-16",
    "book": "Hebrews",
    "chapter": 4,
    "verse": 16,
    "text": "Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need.",
    "translation": "WEB",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse"
  },
  {
    "id": "web-luke-15-20",
    "book": "Luke",
    "chapter": 15,
    "verse": 20,
    "text": "“He arose, and came to his father. But while he was still far off, his father saw him, and was moved with compassion, and ran, and fell on his neck, and kissed him.",
    "translation": "WEB",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse,guilt"
  },
  {
    "id": "web-2corinthians-12-9",
    "book": "2 Corinthians",
    "chapter": 12,
    "verse": 9,
    "text": "He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.",
    "translation": "WEB",
    "primary_emotion_tag": "weakness",
    "secondary_tags": "shame,strength"
  },
  {
    "id": "web-1john-1-9",
    "book": "1 John",
    "chapter": 1,
    "verse": 9,
    "text": "If we confess our sins, he is faithful and righteous to forgive us the sins, and to cleanse us from all unrighteousness.",
    "translation": "WEB",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse,shame"
  },
  {
    "id": "web-psalms-51-10",
    "book": "Psalms",
    "chapter": 51,
    "verse": 10,
    "text": "Create in me a clean heart, O God. Renew a right spirit within me.",
    "translation": "WEB",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse"
  },
  {
    "id": "web-proverbs-24-16",
    "book": "Proverbs",
    "chapter": 24,
    "verse": 16,
    "text": "for a righteous man falls seven times and rises up again; but the wicked are overthrown by calamity.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "web-micah-7-8",
    "book": "Micah",
    "chapter": 7,
    "verse": 8,
    "text": "Don’t rejoice against me, my enemy. When I fall, I will arise. When I sit in darkness, Yahweh will be a light to me.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "shame,hope"
  },
  {
    "id": "web-2corinthians-5-17",
    "book": "2 Corinthians",
    "chapter": 5,
    "verse": 17,
    "text": "Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,identity"
  },
  {
    "id": "web-lamentations-3-22",
    "book": "Lamentations",
    "chapter": 3,
    "verse": 22,
    "text": "It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,guilt"
  },
  {
    "id": "web-lamentations-3-23",
    "book": "Lamentations",
    "chapter": 3,
    "verse": 23,
    "text": "They are new every morning. Great is your faithfulness.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "web-psalms-40-2",
    "book": "Psalms",
    "chapter": 40,
    "verse": 2,
    "text": "He brought me up also out of a horrible pit, out of the miry clay. He set my feet on a rock, and gave me a firm place to stand.",
    "translation": "WEB",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "relapse"
  },
  {
    "id": "web-psalms-34-18",
    "book": "Psalms",
    "chapter": 34,
    "verse": 18,
    "text": "Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit.",
    "translation": "WEB",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "grief,loneliness"
  },
  {
    "id": "web-psalms-147-3",
    "book": "Psalms",
    "chapter": 147,
    "verse": 3,
    "text": "He heals the broken in heart, and binds up their wounds.",
    "translation": "WEB",
    "primary_emotion_tag": "grief",
    "secondary_tags": "hurt"
  },
  {
    "id": "web-psalms-23-4",
    "book": "Psalms",
    "chapter": 23,
    "verse": 4,
    "text": "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "grief"
  },
  {
    "id": "web-isaiah-41-10",
    "book": "Isaiah",
    "chapter": 41,
    "verse": 10,
    "text": "Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "anxiety,strength"
  },
  {
    "id": "web-joshua-1-9",
    "book": "Joshua",
    "chapter": 1,
    "verse": 9,
    "text": "Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go.”",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "strength"
  },
  {
    "id": "web-deuteronomy-31-6",
    "book": "Deuteronomy",
    "chapter": 31,
    "verse": 6,
    "text": "Be strong and courageous. Don’t be afraid or scared of them; for Yahweh your God himself is who goes with you. He will not fail you nor forsake you.”",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "loneliness"
  },
  {
    "id": "web-2timothy-1-7",
    "book": "2 Timothy",
    "chapter": 1,
    "verse": 7,
    "text": "For God didn’t give us a spirit of fear, but of power, love, and self-control.",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "self_control"
  },
  {
    "id": "web-philippians-4-6",
    "book": "Philippians",
    "chapter": 4,
    "verse": 6,
    "text": "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.",
    "translation": "WEB",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "web-philippians-4-7",
    "book": "Philippians",
    "chapter": 4,
    "verse": 7,
    "text": "And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",
    "translation": "WEB",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "peace"
  },
  {
    "id": "web-1peter-5-7",
    "book": "1 Peter",
    "chapter": 5,
    "verse": 7,
    "text": "casting all your worries on him, because he cares for you.",
    "translation": "WEB",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "web-matthew-11-28",
    "book": "Matthew",
    "chapter": 11,
    "verse": 28,
    "text": "“Come to me, all you who labor and are heavily burdened, and I will give you rest.",
    "translation": "WEB",
    "primary_emotion_tag": "stress",
    "secondary_tags": "exhaustion,rest"
  },
  {
    "id": "web-john-16-33",
    "book": "John",
    "chapter": 16,
    "verse": 33,
    "text": "I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.”",
    "translation": "WEB",
    "primary_emotion_tag": "stress",
    "secondary_tags": "hope"
  },
  {
    "id": "web-isaiah-40-31",
    "book": "Isaiah",
    "chapter": 40,
    "verse": 31,
    "text": "but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.",
    "translation": "WEB",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "weakness,strength"
  },
  {
    "id": "web-galatians-6-9",
    "book": "Galatians",
    "chapter": 6,
    "verse": 9,
    "text": "Let’s not be weary in doing good, for we will reap in due season, if we don’t give up.",
    "translation": "WEB",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "perseverance"
  },
  {
    "id": "web-hebrews-12-1",
    "book": "Hebrews",
    "chapter": 12,
    "verse": 1,
    "text": "Therefore let’s also, seeing we are surrounded by so great a cloud of witnesses, lay aside every weight and the sin which so easily entangles us, and let’s run with perseverance the race that is set before us,",
    "translation": "WEB",
    "primary_emotion_tag": "perseverance",
    "secondary_tags": "temptation"
  },
  {
    "id": "web-philippians-4-13",
    "book": "Philippians",
    "chapter": 4,
    "verse": 13,
    "text": "I can do all things through Christ, who strengthens me.",
    "translation": "WEB",
    "primary_emotion_tag": "strength",
    "secondary_tags": "weakness"
  },
  {
    "id": "web-ecclesiastes-4-10",
    "book": "Ecclesiastes",
    "chapter": 4,
    "verse": 10,
    "text": "For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn’t have another to lift him up.",
    "translation": "WEB",
    "primary_emotion_tag": "loneliness",
    "secondary_tags": "community"
  },
  {
    "id": "web-ephesians-4-26",
    "book": "Ephesians",
    "chapter": 4,
    "verse": 26,
    "text": "“Be angry, and don’t sin.” Don’t let the sun go down on your wrath,",
    "translation": "WEB",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "web-james-1-19",
    "book": "James",
    "chapter": 1,
    "verse": 19,
    "text": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "translation": "WEB",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "web-proverbs-3-5",
    "book": "Proverbs",
    "chapter": 3,
    "verse": 5,
    "text": "Trust in Yahweh with all your heart, and don’t lean on your own understanding.",
    "translation": "WEB",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "trust"
  },
  {
    "id": "web-psalms-139-23",
    "book": "Psalms",
    "chapter": 139,
    "verse": 23,
    "text": "Search me, God, and know my heart. Try me, and know my thoughts.",
    "translation": "WEB",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "self_examination"
  },
  {
    "id": "web-ephesians-5-18",
    "book": "Ephesians",
    "chapter": 5,
    "verse": 18,
    "text": "Don’t be drunken with wine, in which is dissipation, but be filled with the Spirit,",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "web-proverbs-20-1",
    "book": "Proverbs",
    "chapter": 20,
    "verse": 1,
    "text": "Wine is a mocker and beer is a brawler. Whoever is led astray by them is not wise.",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "web-1corinthians-6-12",
    "book": "1 Corinthians",
    "chapter": 6,
    "verse": 12,
    "text": "“All things are lawful for me,” but not all things are expedient. “All things are lawful for me,” but I will not be brought under the power of anything.",
    "translation": "WEB",
    "primary_emotion_tag": "habit",
    "secondary_tags": "digital,behavioral"
  },
  {
    "id": "web-psalms-101-3",
    "book": "Psalms",
    "chapter": 101,
    "verse": 3,
    "text": "I will set no vile thing before my eyes. I hate the deeds of faithless men. They will not cling to me.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "digital,pornography"
  },
  {
    "id": "web-job-31-1",
    "book": "Job",
    "chapter": 31,
    "verse": 1,
    "text": "“I made a covenant with my eyes, how then should I look lustfully at a young woman?",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "pornography"
  }
];
