// GENERATED by scripts/build-scripture-seed.mjs. Do not edit by hand.
// Sources and licences: docs/bible-data.md
import type { ScriptureRow } from '../types';

export const SCRIPTURE_SEED: ScriptureRow[] = [
  {
    "id": "web-1corinthians-10-13",
    "book": "1 Corinthians",
    "chapter": 10,
    "verse": 13,
    "text": "No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape, that you may be able to endure it.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "lsg-1corinthians-10-13",
    "book": "1 Corinthiens",
    "chapter": 10,
    "verse": 13,
    "text": "Aucune tentation ne vous est survenue qui n'ait été humaine, et Dieu, qui est fidèle, ne permettra pas que vous soyez tentés au delà de vos forces; mais avec la tentation il préparera aussi le moyen d'en sortir, afin que vous puissiez la supporter.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "igbo-1corinthians-10-13",
    "book": "I. Ndi Kọrint",
    "chapter": 10,
    "verse": 13,
    "text": "Ọ dighi ọnwunwa ọ bula nwaworo unu ma-ọbughi nke madu nānagide: ma Chineke kwesiri ntukwasi-obi, Onye nāgaghi-ekwe ka anwa unu kari nke unu puru inagide; kama n'oge ọnwunwa ahu Ọ gēme kwa uzọ nb͕apu, ka unu we nwe ike inagide ya.",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "web-james-4-7",
    "book": "James",
    "chapter": 4,
    "verse": 7,
    "text": "Be subject therefore to God. Resist the devil, and he will flee from you.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "lsg-james-4-7",
    "book": "Jacques",
    "chapter": 4,
    "verse": 7,
    "text": "Soumettez-vous donc à Dieu; résistez au diable, et il fuira loin de vous.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "igbo-james-4-7",
    "book": "Jemes",
    "chapter": 4,
    "verse": 7,
    "text": "Ya mere donu onwe-unu n'okpuru Chineke; ma guzogidenu ekwesu, ọ gāb͕apu kwa n'ebe unu nọ.",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "strength,craving"
  },
  {
    "id": "web-1peter-5-8",
    "book": "1 Peter",
    "chapter": 5,
    "verse": 8,
    "text": "Be sober and self-controlled. Be watchful. Your adversary, the devil, walks around like a roaring lion, seeking whom he may devour.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "vigilance"
  },
  {
    "id": "lsg-1peter-5-8",
    "book": "1 Pierre",
    "chapter": 5,
    "verse": 8,
    "text": "Soyez sobres, veillez. Votre adversaire, le diable, rôde comme un lion rugissant, cherchant qui il dévorera.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "vigilance"
  },
  {
    "id": "igbo-1peter-5-8",
    "book": "I. Pita",
    "chapter": 5,
    "verse": 8,
    "text": "Nwenu anya-udo, nēchenu nche: onye ahu nke nēkuru unu ga ikpé, bú ekwensu, dika ọdum nāb͕ọ uja, ọ nējeghari, nāchọ onye o gēlomi:",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "vigilance"
  },
  {
    "id": "web-hebrews-4-15",
    "book": "Hebrews",
    "chapter": 4,
    "verse": 15,
    "text": "For we don’t have a high priest who can’t be touched with the feeling of our infirmities, but one who has been in all points tempted like we are, yet without sin.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "shame"
  },
  {
    "id": "lsg-hebrews-4-15",
    "book": "Hébreux",
    "chapter": 4,
    "verse": 15,
    "text": "Car nous n'avons pas un souverain sacrificateur qui ne puisse compatir à nos faiblesses; au contraire, il a été tenté comme nous en toutes choses, sans commettre de péché.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "shame"
  },
  {
    "id": "igbo-hebrews-4-15",
    "book": "Ndi-Hibru",
    "chapter": 4,
    "verse": 15,
    "text": "N'ihi na ayi enweghi onye-isi-nchu-àjà onye nāpughi iji obi so ayi hukọ ahuhu n'adighi- ike-ayi; kama ayi nwere Onye anwaworo n'ihe nile n'otù uzọ ahu anānwa ayi, ma O mehieghi.",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "shame"
  },
  {
    "id": "web-galatians-5-1",
    "book": "Galatians",
    "chapter": 5,
    "verse": 1,
    "text": "Stand firm therefore in the liberty by which Christ has made us free, and don’t be entangled again with a yoke of bondage.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "freedom"
  },
  {
    "id": "lsg-galatians-5-1",
    "book": "Galates",
    "chapter": 5,
    "verse": 1,
    "text": "C'est pour la liberté que Christ nous a affranchis. Demeurez donc fermes, et ne vous laissez pas mettre de nouveau sous le joug de la servitude.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "freedom"
  },
  {
    "id": "igbo-galatians-5-1",
    "book": "Ndi Galetia",
    "chapter": 5,
    "verse": 1,
    "text": "Kraist mere ka ayi pua n'orù ka ayi we nwere onwe-ayi: ya mere nēguzosinu ike, unu ekwela ka ewere yoke nke bu ibu-orù jide unu ọzọ.",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "freedom"
  },
  {
    "id": "web-proverbs-25-28",
    "book": "Proverbs",
    "chapter": 25,
    "verse": 28,
    "text": "Like a city that is broken down and without walls is a man whose spirit is without restraint.",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "lsg-proverbs-25-28",
    "book": "Proverbes",
    "chapter": 25,
    "verse": 28,
    "text": "Comme une ville forcée et sans murailles, Ainsi est l'homme qui n'est pas maître de lui- même.",
    "translation": "LSG",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "igbo-proverbs-25-28",
    "book": "Ilu",
    "chapter": 25,
    "verse": 28,
    "text": "Obodo etikpọrọ etikpọ nke mb͕idi nādighi Ka onye ọ bula nke nādighi-ebọchi mọ-ya bu.",
    "translation": "IGBO",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "wlc-proverbs-25-28",
    "book": "משלי",
    "chapter": 25,
    "verse": 28,
    "text": "עִיר פְּרוּצָה אֵין חוֹמָה אִישׁ אֲשֶׁר אֵין מַעְצָר לְרוּחוֹ׃",
    "translation": "WLC",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "web-titus-2-12",
    "book": "Titus",
    "chapter": 2,
    "verse": 12,
    "text": "instructing us to the intent that, denying ungodliness and worldly lusts, we would live soberly, righteously, and godly in this present age;",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "lsg-titus-2-12",
    "book": "Tite",
    "chapter": 2,
    "verse": 12,
    "text": "Elle nous enseigne à renoncer à l'impiété et aux convoitises mondaines, et à vivre dans le siècle présent selon la sagesse, la justice et la piété,",
    "translation": "LSG",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "igbo-titus-2-12",
    "book": "Taitọs",
    "chapter": 2,
    "verse": 12,
    "text": "nādọ ayi aka na nti ka ayi we ju asọpurughi-Chineke na agu ihe ọjọ di n'uwa, we di ndu uche zuru okè na nke ezi omume na nke isọpuru-Chineke n'oge di ub͕u a;",
    "translation": "IGBO",
    "primary_emotion_tag": "craving",
    "secondary_tags": "self_control"
  },
  {
    "id": "web-philippians-4-8",
    "book": "Philippians",
    "chapter": 4,
    "verse": 8,
    "text": "Finally, brothers, whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report: if there is any virtue and if there is any praise, think about these things.",
    "translation": "WEB",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "craving,mind"
  },
  {
    "id": "lsg-philippians-4-8",
    "book": "Philippiens",
    "chapter": 4,
    "verse": 8,
    "text": "Au reste, frères, que tout ce qui est vrai, tout ce qui est honorable, tout ce qui est juste, tout ce qui est pur, tout ce qui est aimable, tout ce qui mérite l'approbation, ce qui est vertueux et digne de louange, soit l'objet de vos pensées.",
    "translation": "LSG",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "craving,mind"
  },
  {
    "id": "igbo-philippians-4-8",
    "book": "Ndi Filipai",
    "chapter": 4,
    "verse": 8,
    "text": "Nke fọduru, umu-nnam, ka ihe bu ezi-okwu ra, ka ha ra, bú ihe kwesiri nsọpuru, ka ha ra, bú ihe ziri ezi, ka ha ra, bú ihe di ọcha, ka ha ra, bú ihe kwesiri ihu-n'anya, ka ha ra, bú ihe ekwuru nke-ọma; ọ buru na idi-nma ọ bula di, o buru kwa na otuto ọ bula di, nāgukọnu ihe ndia.",
    "translation": "IGBO",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "craving,mind"
  },
  {
    "id": "web-romans-12-2",
    "book": "Romans",
    "chapter": 12,
    "verse": 2,
    "text": "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.",
    "translation": "WEB",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "habit,mind"
  },
  {
    "id": "lsg-romans-12-2",
    "book": "Romains",
    "chapter": 12,
    "verse": 2,
    "text": "Ne vous conformez pas au siècle présent, mais soyez transformés par le renouvellement de l'intelligence, afin que vous discerniez quelle est la volonté de Dieu, ce qui est bon, agréable et parfait.",
    "translation": "LSG",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "habit,mind"
  },
  {
    "id": "igbo-romans-12-2",
    "book": "Ndi Rom",
    "chapter": 12,
    "verse": 2,
    "text": "Unu ekwe-kwa-la ka eme ka unu yie ajọ oge a: kama ka enwogha unu site n'ime ka uche-unu buru ihe ọhu, ka unu we nwaputa ihe bu ihe Chineke nāchọ, bú ezi ihe nke di kwa Ya ezi utọ nke zu-kwa-ra okè.",
    "translation": "IGBO",
    "primary_emotion_tag": "boredom",
    "secondary_tags": "habit,mind"
  },
  {
    "id": "web-romans-8-1",
    "book": "Romans",
    "chapter": 8,
    "verse": 1,
    "text": "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit.",
    "translation": "WEB",
    "primary_emotion_tag": "shame",
    "secondary_tags": "guilt,relapse"
  },
  {
    "id": "lsg-romans-8-1",
    "book": "Romains",
    "chapter": 8,
    "verse": 1,
    "text": "Il n'y a donc maintenant aucune condamnation pour ceux qui sont en Jésus Christ.",
    "translation": "LSG",
    "primary_emotion_tag": "shame",
    "secondary_tags": "guilt,relapse"
  },
  {
    "id": "igbo-romans-8-1",
    "book": "Ndi Rom",
    "chapter": 8,
    "verse": 1,
    "text": "Ya mere ub͕u a ọ dighi amam-ikpe ọ bula diri ndi nọ nime Kraist Jisus.",
    "translation": "IGBO",
    "primary_emotion_tag": "shame",
    "secondary_tags": "guilt,relapse"
  },
  {
    "id": "web-hebrews-4-16",
    "book": "Hebrews",
    "chapter": 4,
    "verse": 16,
    "text": "Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need.",
    "translation": "WEB",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse"
  },
  {
    "id": "lsg-hebrews-4-16",
    "book": "Hébreux",
    "chapter": 4,
    "verse": 16,
    "text": "Approchons-nous donc avec assurance du trône de la grâce afin d'obtenir miséricorde et de trouver grâce, pour être secourus dans nos besoins.",
    "translation": "LSG",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse"
  },
  {
    "id": "igbo-hebrews-4-16",
    "book": "Ndi-Hibru",
    "chapter": 4,
    "verse": 16,
    "text": "Ya mere ka ayi were nkwuwa-okwu biarue oche-eze amara, ka ewe mere ayi ebere, ka ayi we hu kwa amara iyere ayi aka n'oge nkpà.",
    "translation": "IGBO",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse"
  },
  {
    "id": "web-luke-15-20",
    "book": "Luke",
    "chapter": 15,
    "verse": 20,
    "text": "“He arose, and came to his father. But while he was still far off, his father saw him, and was moved with compassion, and ran, and fell on his neck, and kissed him.",
    "translation": "WEB",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse,guilt"
  },
  {
    "id": "lsg-luke-15-20",
    "book": "Luc",
    "chapter": 15,
    "verse": 20,
    "text": "Et il se leva, et alla vers son père. Comme il était encore loin, son père le vit et fut ému de compassion, il courut se jeter à son cou et le baisa.",
    "translation": "LSG",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse,guilt"
  },
  {
    "id": "igbo-luke-15-20",
    "book": "Luk",
    "chapter": 15,
    "verse": 20,
    "text": "O we bilie, biakute nna-ya. Ma mb͕e ọ nọ n'ebe di anya ub͕u a, nna-ya huru ya, o we nwe ọmiko n'aru-ya, b͕a ọsọ, makua ya n'olu, sutu kwa ya ọnu nke-uku.",
    "translation": "IGBO",
    "primary_emotion_tag": "shame",
    "secondary_tags": "relapse,guilt"
  },
  {
    "id": "web-2corinthians-12-9",
    "book": "2 Corinthians",
    "chapter": 12,
    "verse": 9,
    "text": "He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.",
    "translation": "WEB",
    "primary_emotion_tag": "weakness",
    "secondary_tags": "shame,strength"
  },
  {
    "id": "lsg-2corinthians-12-9",
    "book": "2 Corinthiens",
    "chapter": 12,
    "verse": 9,
    "text": "et il m'a dit: Ma grâce te suffit, car ma puissance s'accomplit dans la faiblesse. Je me glorifierai donc bien plus volontiers de mes faiblesses, afin que la puissance de Christ repose sur moi.",
    "translation": "LSG",
    "primary_emotion_tag": "weakness",
    "secondary_tags": "shame,strength"
  },
  {
    "id": "igbo-2corinthians-12-9",
    "book": "II. Ndi Kọrint",
    "chapter": 12,
    "verse": 9,
    "text": "Ọ siwokwam, Amaram ezuworo gi: n'ihi na emewo ka ikem zu oké n'adighi-ike. Ya mere kama ihe ọzọ m'gēwere obi-utọ nile nya isi n'adighi-ikem nile, ka ike nke Kraist we ridakwasim, biri kwa nimem.",
    "translation": "IGBO",
    "primary_emotion_tag": "weakness",
    "secondary_tags": "shame,strength"
  },
  {
    "id": "web-1john-1-9",
    "book": "1 John",
    "chapter": 1,
    "verse": 9,
    "text": "If we confess our sins, he is faithful and righteous to forgive us the sins, and to cleanse us from all unrighteousness.",
    "translation": "WEB",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse,shame"
  },
  {
    "id": "lsg-1john-1-9",
    "book": "1 Jean",
    "chapter": 1,
    "verse": 9,
    "text": "Si nous confessons nos péchés, il est fidèle et juste pour nous les pardonner, et pour nous purifier de toute iniquité.",
    "translation": "LSG",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse,shame"
  },
  {
    "id": "igbo-1john-1-9",
    "book": "I. Jọn",
    "chapter": 1,
    "verse": 9,
    "text": "Ọ buru na ayi ekwuputa nmehie-ayi, Ọ bu Onye kwesiri ntukwasi-obi, buru kwa Onye ezi omume, ka O we b͕aghara ayi nmehie-ayi, sachapu kwa ayi ajọ omume nile.",
    "translation": "IGBO",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse,shame"
  },
  {
    "id": "web-psalms-51-10",
    "book": "Psalms",
    "chapter": 51,
    "verse": 10,
    "text": "Create in me a clean heart, O God. Renew a right spirit within me.",
    "translation": "WEB",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse"
  },
  {
    "id": "lsg-psalms-51-10",
    "book": "Psaumes",
    "chapter": 51,
    "verse": 10,
    "text": "O Dieu! crée en moi un coeur pur, Renouvelle en moi un esprit bien disposé.",
    "translation": "LSG",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse"
  },
  {
    "id": "igbo-psalms-51-10",
    "book": "Abù Ọma",
    "chapter": 51,
    "verse": 10,
    "text": "Kèrem obi di ọcha, Chineke; Me kwa ka mọ nke nēguzosi ike di ọhu nimem.",
    "translation": "IGBO",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse"
  },
  {
    "id": "wlc-psalms-51-10",
    "book": "תהלים",
    "chapter": 51,
    "verse": 10,
    "text": "לֵב טָהוֹר בְּרָא־לִי אֱלֹהִים וְרוּחַ נָכוֹן חַדֵּשׁ בְּקִרְבִּי׃",
    "translation": "WLC",
    "primary_emotion_tag": "guilt",
    "secondary_tags": "relapse"
  },
  {
    "id": "web-proverbs-24-16",
    "book": "Proverbs",
    "chapter": 24,
    "verse": 16,
    "text": "for a righteous man falls seven times and rises up again; but the wicked are overthrown by calamity.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "lsg-proverbs-24-16",
    "book": "Proverbes",
    "chapter": 24,
    "verse": 16,
    "text": "Car sept fois le juste tombe, et il se relève, Mais les méchants sont précipités dans le malheur.",
    "translation": "LSG",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "igbo-proverbs-24-16",
    "book": "Ilu",
    "chapter": 24,
    "verse": 16,
    "text": "N'ihi na ub͕ò asa ka onye ezi omume nāda, bili kwa ọzọ: Ma ndi nēmebi iwu nāsu ngọngọ n'ihe ọjọ.",
    "translation": "IGBO",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "wlc-proverbs-24-16",
    "book": "משלי",
    "chapter": 24,
    "verse": 16,
    "text": "כִּי שֶׁבַע׀ יִפּוֹל צַדִּיק וָקָם וּרְשָׁעִים יִכָּשְׁלוּ בְרָעָה׃",
    "translation": "WLC",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "web-micah-7-8",
    "book": "Micah",
    "chapter": 7,
    "verse": 8,
    "text": "Don’t rejoice against me, my enemy. When I fall, I will arise. When I sit in darkness, Yahweh will be a light to me.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "shame,hope"
  },
  {
    "id": "lsg-micah-7-8",
    "book": "Michée",
    "chapter": 7,
    "verse": 8,
    "text": "Ne te réjouis pas à mon sujet, mon ennemie! Car si je suis tombée, je me relèverai; Si je suis assise dans les ténèbres, L'Éternel sera ma lumière.",
    "translation": "LSG",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "shame,hope"
  },
  {
    "id": "igbo-micah-7-8",
    "book": "Maika",
    "chapter": 7,
    "verse": 8,
    "text": "Aṅulam ọṅu, gi onye-irom: mb͕e m'dara ada, m'bilie; mb͕e m'nānọdu n'ọchichiri, Jehova gāburum ìhè.",
    "translation": "IGBO",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "shame,hope"
  },
  {
    "id": "wlc-micah-7-8",
    "book": "מיכה",
    "chapter": 7,
    "verse": 8,
    "text": "אַל־תִּשְׂמְחִי אֹיַבְתִּי לִי כִּי נָפַלְתִּי קָמְתִּי כִּי־אֵשֵׁב בַּחֹשֶׁךְ יְהוָה אוֹר לִי׃ס",
    "translation": "WLC",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "shame,hope"
  },
  {
    "id": "web-2corinthians-5-17",
    "book": "2 Corinthians",
    "chapter": 5,
    "verse": 17,
    "text": "Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,identity"
  },
  {
    "id": "lsg-2corinthians-5-17",
    "book": "2 Corinthiens",
    "chapter": 5,
    "verse": 17,
    "text": "Si quelqu'un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées; voici, toutes choses sont devenues nouvelles.",
    "translation": "LSG",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,identity"
  },
  {
    "id": "igbo-2corinthians-5-17",
    "book": "II. Ndi Kọrint",
    "chapter": 5,
    "verse": 17,
    "text": "Ya mere ọ buru na onye ọ bula di nime Kraist, ọ bu onye ekère ọhu: ihe ochie agasiwo; le, ha aghọwo ihe ọhu.",
    "translation": "IGBO",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,identity"
  },
  {
    "id": "web-lamentations-3-22",
    "book": "Lamentations",
    "chapter": 3,
    "verse": 22,
    "text": "It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,guilt"
  },
  {
    "id": "lsg-lamentations-3-22",
    "book": "Lamentations",
    "chapter": 3,
    "verse": 22,
    "text": "Les bontés de l'Éternel ne sont pas épuisés, Ses compassions ne sont pas à leur terme;",
    "translation": "LSG",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,guilt"
  },
  {
    "id": "igbo-lamentations-3-22",
    "book": "Abù-Ákwá",
    "chapter": 3,
    "verse": 22,
    "text": "O sitere n'ebere nile nke Jehova na emeghi ka ayi gwusia, n'ihi na obi-ebere-Ya nile agwughi.",
    "translation": "IGBO",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,guilt"
  },
  {
    "id": "wlc-lamentations-3-22",
    "book": "איכה",
    "chapter": 3,
    "verse": 22,
    "text": "חַסְדֵי יְהוָה כִּי לֹא־תָמְנוּ כִּי לֹא־כָלוּ רַחֲמָיו׃",
    "translation": "WLC",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope,guilt"
  },
  {
    "id": "web-lamentations-3-23",
    "book": "Lamentations",
    "chapter": 3,
    "verse": 23,
    "text": "They are new every morning. Great is your faithfulness.",
    "translation": "WEB",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "lsg-lamentations-3-23",
    "book": "Lamentations",
    "chapter": 3,
    "verse": 23,
    "text": "Elles se renouvellent chaque matin. Oh! que ta fidélité est grande!",
    "translation": "LSG",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "igbo-lamentations-3-23",
    "book": "Abù-Ákwá",
    "chapter": 3,
    "verse": 23,
    "text": "Ha di ọhu kwa-ututu; ihe riri nne ka ikwesi-ntukwasi-obi-Gi bu.",
    "translation": "IGBO",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "wlc-lamentations-3-23",
    "book": "איכה",
    "chapter": 3,
    "verse": 23,
    "text": "חֲדָשִׁים לַבְּקָרִים רַבָּה אֱמוּנָתֶךָ׃",
    "translation": "WLC",
    "primary_emotion_tag": "relapse",
    "secondary_tags": "hope"
  },
  {
    "id": "web-psalms-40-2",
    "book": "Psalms",
    "chapter": 40,
    "verse": 2,
    "text": "He brought me up also out of a horrible pit, out of the miry clay. He set my feet on a rock, and gave me a firm place to stand.",
    "translation": "WEB",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "relapse"
  },
  {
    "id": "lsg-psalms-40-2",
    "book": "Psaumes",
    "chapter": 40,
    "verse": 2,
    "text": "Il m'a retiré de la fosse de destruction, Du fond de la boue; Et il a dressé mes pieds sur le roc, Il a affermi mes pas.",
    "translation": "LSG",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "relapse"
  },
  {
    "id": "igbo-psalms-40-2",
    "book": "Abù Ọma",
    "chapter": 40,
    "verse": 2,
    "text": "Ọ we me ka m'si n'olùlù nbibi, n'apiti nke ala urọ, rigoputa; Ọ we me ka ukwum abua guzo n'elu nkume di elu, Ọ nēme ka nzọ-ukwum nile guzosie ike.",
    "translation": "IGBO",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "relapse"
  },
  {
    "id": "wlc-psalms-40-2",
    "book": "תהלים",
    "chapter": 40,
    "verse": 2,
    "text": "וַיַּעֲלֵנִי׀ מִבּוֹר שָׁאוֹן מִטִּיט הַיָּוֵן וַיָּקֶם עַל־סֶלַע רַגְלַי כּוֹנֵן אֲשֻׁרָי׃",
    "translation": "WLC",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "relapse"
  },
  {
    "id": "web-psalms-34-18",
    "book": "Psalms",
    "chapter": 34,
    "verse": 18,
    "text": "Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit.",
    "translation": "WEB",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "grief,loneliness"
  },
  {
    "id": "lsg-psalms-34-18",
    "book": "Psaumes",
    "chapter": 34,
    "verse": 18,
    "text": "L'Éternel est près de ceux qui ont le coeur brisé, Et il sauve ceux qui ont l'esprit dans l'abattement.",
    "translation": "LSG",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "grief,loneliness"
  },
  {
    "id": "igbo-psalms-34-18",
    "book": "Abù Ọma",
    "chapter": 34,
    "verse": 18,
    "text": "Jehova nọ nso ndi obi-ha tiwara etiwa, Ọ nāzọputa kwa ndi azọpiaworo nime mọ-ha.",
    "translation": "IGBO",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "grief,loneliness"
  },
  {
    "id": "wlc-psalms-34-18",
    "book": "תהלים",
    "chapter": 34,
    "verse": 18,
    "text": "קָרוֹב יְהוָה לְנִשְׁבְּרֵי־לֵב וְאֶת־דַּכְּאֵי־רוּחַ יוֹשִׁיעַ׃",
    "translation": "WLC",
    "primary_emotion_tag": "hopelessness",
    "secondary_tags": "grief,loneliness"
  },
  {
    "id": "web-psalms-147-3",
    "book": "Psalms",
    "chapter": 147,
    "verse": 3,
    "text": "He heals the broken in heart, and binds up their wounds.",
    "translation": "WEB",
    "primary_emotion_tag": "grief",
    "secondary_tags": "hurt"
  },
  {
    "id": "lsg-psalms-147-3",
    "book": "Psaumes",
    "chapter": 147,
    "verse": 3,
    "text": "Il guérit ceux qui ont le coeur brisé, Et il panse leurs blessures.",
    "translation": "LSG",
    "primary_emotion_tag": "grief",
    "secondary_tags": "hurt"
  },
  {
    "id": "igbo-psalms-147-3",
    "book": "Abù Ọma",
    "chapter": 147,
    "verse": 3,
    "text": "Ọ bu onye nēme ka ndi obi-ha tiwara etiwa diri ndu, Ọ nēkechi kwa ihe-nb͕u nile ha.",
    "translation": "IGBO",
    "primary_emotion_tag": "grief",
    "secondary_tags": "hurt"
  },
  {
    "id": "wlc-psalms-147-3",
    "book": "תהלים",
    "chapter": 147,
    "verse": 3,
    "text": "הָרֹפֵא לִשְׁבוּרֵי לֵב וּמְחַבֵּשׁ לְעַצְּבוֹתָם׃",
    "translation": "WLC",
    "primary_emotion_tag": "grief",
    "secondary_tags": "hurt"
  },
  {
    "id": "web-psalms-23-4",
    "book": "Psalms",
    "chapter": 23,
    "verse": 4,
    "text": "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "grief"
  },
  {
    "id": "lsg-psalms-23-4",
    "book": "Psaumes",
    "chapter": 23,
    "verse": 4,
    "text": "Quand je marche dans la vallée de l'ombre de la mort, Je ne crains aucun mal, car tu es avec moi: Ta houlette et ton bâton me rassurent.",
    "translation": "LSG",
    "primary_emotion_tag": "fear",
    "secondary_tags": "grief"
  },
  {
    "id": "igbo-psalms-23-4",
    "book": "Abù Ọma",
    "chapter": 23,
    "verse": 4,
    "text": "Ọzọ, asi na ejem ije na ndagwurugwu onyinyo ọnwu, M'gaghi-atu egwu ihe ọjọ ọ bula; n'ihi na Gi onwe-gi nọyerem: Ndele-Gi na nkpa-n'aka-Gi, ha onwe-ha nākasim obi.",
    "translation": "IGBO",
    "primary_emotion_tag": "fear",
    "secondary_tags": "grief"
  },
  {
    "id": "wlc-psalms-23-4",
    "book": "תהלים",
    "chapter": 23,
    "verse": 4,
    "text": "גַּם כִּי־אֵלֵךְ בְּגֵיא צַלְמָוֶת לֹא־אִירָא רָע כִּי־אַתָּה עִמָּדִי שִׁבְטְךָ וּמִשְׁעַנְתֶּךָ הֵמָּה יְנַחֲמֻנִי׃",
    "translation": "WLC",
    "primary_emotion_tag": "fear",
    "secondary_tags": "grief"
  },
  {
    "id": "web-isaiah-41-10",
    "book": "Isaiah",
    "chapter": 41,
    "verse": 10,
    "text": "Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "anxiety,strength"
  },
  {
    "id": "lsg-isaiah-41-10",
    "book": "Esaïe",
    "chapter": 41,
    "verse": 10,
    "text": "Ne crains rien, car je suis avec toi; Ne promène pas des regards inquiets, car je suis ton Dieu; Je te fortifie, je viens à ton secours, Je te soutiens de ma droite triomphante.",
    "translation": "LSG",
    "primary_emotion_tag": "fear",
    "secondary_tags": "anxiety,strength"
  },
  {
    "id": "igbo-isaiah-41-10",
    "book": "Aisaia",
    "chapter": 41,
    "verse": 10,
    "text": "atula egwu, gi ka M'nọyere: elela anya buruburu n'ujọ, n'ihi na Mu onwem bu Chineke- gi: M'gāb͕a gi ume; e, M'gēyere gi aka; e, M'gēji aka-nri nke ezi omumem kwagide gi.",
    "translation": "IGBO",
    "primary_emotion_tag": "fear",
    "secondary_tags": "anxiety,strength"
  },
  {
    "id": "wlc-isaiah-41-10",
    "book": "ישעיהו",
    "chapter": 41,
    "verse": 10,
    "text": "אַל־תִּירָא כִּי עִמְּךָ־אָנִי אַל־תִּשְׁתָּע כִּי־אֲנִי אֱלֹהֶיךָ אִמַּצְתִּיךָ אַף־עֲזַרְתִּיךָ אַף־תְּמַכְתִּיךָ בִּימִין צִדְקִי׃",
    "translation": "WLC",
    "primary_emotion_tag": "fear",
    "secondary_tags": "anxiety,strength"
  },
  {
    "id": "web-joshua-1-9",
    "book": "Joshua",
    "chapter": 1,
    "verse": 9,
    "text": "Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go.”",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "strength"
  },
  {
    "id": "lsg-joshua-1-9",
    "book": "Josué",
    "chapter": 1,
    "verse": 9,
    "text": "Ne t'ai-je pas donné cet ordre: Fortifie-toi et prends courage? Ne t'effraie point et ne t'épouvante point, car l'Éternel, ton Dieu, est avec toi dans tout ce que tu entreprendras.",
    "translation": "LSG",
    "primary_emotion_tag": "fear",
    "secondary_tags": "strength"
  },
  {
    "id": "igbo-joshua-1-9",
    "book": "Joshua",
    "chapter": 1,
    "verse": 9,
    "text": "Ènyeghm i iwu? Di ike, nwe kwa ume; amala jijiji, atu-kwa-la ujọ: n'ihi na Jehova, bú Chineke-gi, nọyere gi n'ebe ọ bula i nēje.",
    "translation": "IGBO",
    "primary_emotion_tag": "fear",
    "secondary_tags": "strength"
  },
  {
    "id": "wlc-joshua-1-9",
    "book": "יהושע",
    "chapter": 1,
    "verse": 9,
    "text": "הֲלוֹא צִוִּיתִיךָ חֲזַק וֶאֱמָץ אַל־תַּעֲרֹץ וְאַל־תֵּחָת כִּי עִמְּךָ יְהוָה אֱלֹהֶיךָ בְּכֹל אֲשֶׁר תֵּלֵךְ׃פ",
    "translation": "WLC",
    "primary_emotion_tag": "fear",
    "secondary_tags": "strength"
  },
  {
    "id": "web-deuteronomy-31-6",
    "book": "Deuteronomy",
    "chapter": 31,
    "verse": 6,
    "text": "Be strong and courageous. Don’t be afraid or scared of them; for Yahweh your God himself is who goes with you. He will not fail you nor forsake you.”",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "loneliness"
  },
  {
    "id": "lsg-deuteronomy-31-6",
    "book": "Deutéronome",
    "chapter": 31,
    "verse": 6,
    "text": "Fortifiez-vous et ayez du courage! Ne craignez point et ne soyez point effrayés devant eux; car l'Éternel, ton Dieu, marchera lui-même avec toi, il ne te délaissera point, il ne t'abandonnera point.",
    "translation": "LSG",
    "primary_emotion_tag": "fear",
    "secondary_tags": "loneliness"
  },
  {
    "id": "igbo-deuteronomy-31-6",
    "book": "Deuteronomi",
    "chapter": 31,
    "verse": 6,
    "text": "Dinu ike, nwe-kwa-nu ume, unu atula egwu, unu ama-kwa-la jijiji n'iru ha; n'ihi na Jehova, bú Chineke-gi, Ya onwe-ya bu onye gi na Ya nēje; Ọ gaghi-ara gi aka, Ọ gaghi- arapu kwa gi.",
    "translation": "IGBO",
    "primary_emotion_tag": "fear",
    "secondary_tags": "loneliness"
  },
  {
    "id": "wlc-deuteronomy-31-6",
    "book": "דברים",
    "chapter": 31,
    "verse": 6,
    "text": "חִזְקוּ וְאִמְצוּ אַל־תִּירְאוּ וְאַל־תַּעַרְצוּ מִפְּנֵיהֶם כִּי׀ יְהוָה אֱלֹהֶיךָ הוּא הַהֹלֵךְ עִמָּךְ לֹא יַרְפְּךָ וְלֹא יַעַזְבֶךָּ׃פ",
    "translation": "WLC",
    "primary_emotion_tag": "fear",
    "secondary_tags": "loneliness"
  },
  {
    "id": "web-2timothy-1-7",
    "book": "2 Timothy",
    "chapter": 1,
    "verse": 7,
    "text": "For God didn’t give us a spirit of fear, but of power, love, and self-control.",
    "translation": "WEB",
    "primary_emotion_tag": "fear",
    "secondary_tags": "self_control"
  },
  {
    "id": "lsg-2timothy-1-7",
    "book": "2 Timothée",
    "chapter": 1,
    "verse": 7,
    "text": "Car ce n'est pas un esprit de timidité que Dieu nous a donné, mais un esprit de force, d'amour et de sagesse.",
    "translation": "LSG",
    "primary_emotion_tag": "fear",
    "secondary_tags": "self_control"
  },
  {
    "id": "igbo-2timothy-1-7",
    "book": "II. Timọti",
    "chapter": 1,
    "verse": 7,
    "text": "N'ihi na Chineke enyeghi ayi mọ nke ujọ; kama ọ bu nke ike na ihunanya na ime ka uche zuo okè.",
    "translation": "IGBO",
    "primary_emotion_tag": "fear",
    "secondary_tags": "self_control"
  },
  {
    "id": "web-philippians-4-6",
    "book": "Philippians",
    "chapter": 4,
    "verse": 6,
    "text": "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.",
    "translation": "WEB",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "lsg-philippians-4-6",
    "book": "Philippiens",
    "chapter": 4,
    "verse": 6,
    "text": "Ne vous inquiétez de rien; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces.",
    "translation": "LSG",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "igbo-philippians-4-6",
    "book": "Ndi Filipai",
    "chapter": 4,
    "verse": 6,
    "text": "Unu echeb͕ula onwe-unu n'ihe ọ bula; kama n'ihe nile ọ bula site n'ekpere na aririọ, ya na ekele, menu ka Chineke mara ihe nile unu nāriọ.",
    "translation": "IGBO",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "web-philippians-4-7",
    "book": "Philippians",
    "chapter": 4,
    "verse": 7,
    "text": "And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",
    "translation": "WEB",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "peace"
  },
  {
    "id": "lsg-philippians-4-7",
    "book": "Philippiens",
    "chapter": 4,
    "verse": 7,
    "text": "Et la paix de Dieu, qui surpasse toute intelligence, gardera vos coeurs et vos pensées en Jésus Christ.",
    "translation": "LSG",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "peace"
  },
  {
    "id": "igbo-philippians-4-7",
    "book": "Ndi Filipai",
    "chapter": 4,
    "verse": 7,
    "text": "Udo nke Chineke, nke kachasi uche nile, gēche kwa obi-unu na èchìchè-uche-unu nche nime Kraist Jisus.",
    "translation": "IGBO",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "peace"
  },
  {
    "id": "web-1peter-5-7",
    "book": "1 Peter",
    "chapter": 5,
    "verse": 7,
    "text": "casting all your worries on him, because he cares for you.",
    "translation": "WEB",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "lsg-1peter-5-7",
    "book": "1 Pierre",
    "chapter": 5,
    "verse": 7,
    "text": "et déchargez-vous sur lui de tous vos soucis, car lui-même prend soin de vous.",
    "translation": "LSG",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "igbo-1peter-5-7",
    "book": "I. Pita",
    "chapter": 5,
    "verse": 7,
    "text": "nātukwasinu Ya ncheb͕u nile unu nēcheb͕u onwe-unu, n'ihi na ihe nile bayere unu nēmetu Ya n'obi.",
    "translation": "IGBO",
    "primary_emotion_tag": "anxiety",
    "secondary_tags": "stress"
  },
  {
    "id": "web-matthew-11-28",
    "book": "Matthew",
    "chapter": 11,
    "verse": 28,
    "text": "“Come to me, all you who labor and are heavily burdened, and I will give you rest.",
    "translation": "WEB",
    "primary_emotion_tag": "stress",
    "secondary_tags": "exhaustion,rest"
  },
  {
    "id": "lsg-matthew-11-28",
    "book": "Matthieu",
    "chapter": 11,
    "verse": 28,
    "text": "Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.",
    "translation": "LSG",
    "primary_emotion_tag": "stress",
    "secondary_tags": "exhaustion,rest"
  },
  {
    "id": "igbo-matthew-11-28",
    "book": "Matiu",
    "chapter": 11,
    "verse": 28,
    "text": "Biakutenum, unu nile ndi nādọb͕u onwe-unu n'ọlu, ndi ebowo-kwa-ra ibu di arọọ́, Mu onwem gēme kwa ka unu zuru ike.",
    "translation": "IGBO",
    "primary_emotion_tag": "stress",
    "secondary_tags": "exhaustion,rest"
  },
  {
    "id": "web-john-16-33",
    "book": "John",
    "chapter": 16,
    "verse": 33,
    "text": "I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.”",
    "translation": "WEB",
    "primary_emotion_tag": "stress",
    "secondary_tags": "hope"
  },
  {
    "id": "lsg-john-16-33",
    "book": "Jean",
    "chapter": 16,
    "verse": 33,
    "text": "Je vous ai dit ces choses, afin que vous ayez la paix en moi. Vous aurez des tribulations dans le monde; mais prenez courage, j'ai vaincu le monde.",
    "translation": "LSG",
    "primary_emotion_tag": "stress",
    "secondary_tags": "hope"
  },
  {
    "id": "igbo-john-16-33",
    "book": "Jọn",
    "chapter": 16,
    "verse": 33,
    "text": "Okwu ndia ka M'gwaworo unu, ka unu we nwe udo nimem. N'uwa unu nēnwe nkpab͕u: ma nwenu obi-ike; Mu onwem emeriwo uwa.",
    "translation": "IGBO",
    "primary_emotion_tag": "stress",
    "secondary_tags": "hope"
  },
  {
    "id": "web-isaiah-40-31",
    "book": "Isaiah",
    "chapter": 40,
    "verse": 31,
    "text": "but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.",
    "translation": "WEB",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "weakness,strength"
  },
  {
    "id": "lsg-isaiah-40-31",
    "book": "Esaïe",
    "chapter": 40,
    "verse": 31,
    "text": "Mais ceux qui se confient en l'Éternel renouvellent leur force. Ils prennent le vol comme les aigles; Ils courent, et ne se lassent point, Ils marchent, et ne se fatiguent point.",
    "translation": "LSG",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "weakness,strength"
  },
  {
    "id": "igbo-isaiah-40-31",
    "book": "Aisaia",
    "chapter": 40,
    "verse": 31,
    "text": "ma ndi nēle anya Jehova gāb͕anwe ike-ha; ha gēfego elu na nkù dika ugo; ha gāb͕a ọsọ, ike agaghi-agwu kwa ha; ha gēje ije, ghara ida #mbà.",
    "translation": "IGBO",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "weakness,strength"
  },
  {
    "id": "wlc-isaiah-40-31",
    "book": "ישעיהו",
    "chapter": 40,
    "verse": 31,
    "text": "וְקוֹיֵ יְהוָה יַחֲלִיפוּ כֹחַ יַעֲלוּ אֵבֶר כַּנְּשָׁרִים יָרוּצוּ וְלֹא יִיגָעוּ יֵלְכוּ וְלֹא יִיעָפוּ׃פ",
    "translation": "WLC",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "weakness,strength"
  },
  {
    "id": "web-galatians-6-9",
    "book": "Galatians",
    "chapter": 6,
    "verse": 9,
    "text": "Let’s not be weary in doing good, for we will reap in due season, if we don’t give up.",
    "translation": "WEB",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "perseverance"
  },
  {
    "id": "lsg-galatians-6-9",
    "book": "Galates",
    "chapter": 6,
    "verse": 9,
    "text": "Ne nous lassons pas de faire le bien; car nous moissonnerons au temps convenable, si nous ne nous relâchons pas.",
    "translation": "LSG",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "perseverance"
  },
  {
    "id": "igbo-galatians-6-9",
    "book": "Ndi Galetia",
    "chapter": 6,
    "verse": 9,
    "text": "Ma ike agwula ayi n'obi n'ime ihe ọma: n'ihi na ayi gēweta ihe-ubi mb͕e oge-ya ruru, ma ayi adaghi #mbà.",
    "translation": "IGBO",
    "primary_emotion_tag": "exhaustion",
    "secondary_tags": "perseverance"
  },
  {
    "id": "web-hebrews-12-1",
    "book": "Hebrews",
    "chapter": 12,
    "verse": 1,
    "text": "Therefore let’s also, seeing we are surrounded by so great a cloud of witnesses, lay aside every weight and the sin which so easily entangles us, and let’s run with perseverance the race that is set before us,",
    "translation": "WEB",
    "primary_emotion_tag": "perseverance",
    "secondary_tags": "temptation"
  },
  {
    "id": "lsg-hebrews-12-1",
    "book": "Hébreux",
    "chapter": 12,
    "verse": 1,
    "text": "Nous donc aussi, puisque nous sommes environnés d'une si grande nuée de témoins, rejetons tout fardeau, et le péché qui nous enveloppe si facilement, et courons avec persévérance dans la carrière qui nous est ouverte,",
    "translation": "LSG",
    "primary_emotion_tag": "perseverance",
    "secondary_tags": "temptation"
  },
  {
    "id": "igbo-hebrews-12-1",
    "book": "Ndi-Hibru",
    "chapter": 12,
    "verse": 1,
    "text": "Ya mere ka ayi onwe-ayi, ebe ayi nwere oké ìgwè ndi-àmà di otú a ndi b͕ara ayi gburugburu dika igwe-oji, ka ayi tupu kwa ibu nile ọ bula, ya na nmehie ahu nke nārapara ayi n'aru nke-uku, ka ayi were kwa ntachi-obi b͕a ọsọ ahu edebere ayi n'iru,",
    "translation": "IGBO",
    "primary_emotion_tag": "perseverance",
    "secondary_tags": "temptation"
  },
  {
    "id": "web-philippians-4-13",
    "book": "Philippians",
    "chapter": 4,
    "verse": 13,
    "text": "I can do all things through Christ, who strengthens me.",
    "translation": "WEB",
    "primary_emotion_tag": "strength",
    "secondary_tags": "weakness"
  },
  {
    "id": "lsg-philippians-4-13",
    "book": "Philippiens",
    "chapter": 4,
    "verse": 13,
    "text": "Je puis tout par celui qui me fortifie.",
    "translation": "LSG",
    "primary_emotion_tag": "strength",
    "secondary_tags": "weakness"
  },
  {
    "id": "igbo-philippians-4-13",
    "book": "Ndi Filipai",
    "chapter": 4,
    "verse": 13,
    "text": "Enwerem ike n'ihe nile nime Onye ahu Nke nēmem ka m'di ike.",
    "translation": "IGBO",
    "primary_emotion_tag": "strength",
    "secondary_tags": "weakness"
  },
  {
    "id": "web-ecclesiastes-4-10",
    "book": "Ecclesiastes",
    "chapter": 4,
    "verse": 10,
    "text": "For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn’t have another to lift him up.",
    "translation": "WEB",
    "primary_emotion_tag": "loneliness",
    "secondary_tags": "community"
  },
  {
    "id": "lsg-ecclesiastes-4-10",
    "book": "Ecclésiaste",
    "chapter": 4,
    "verse": 10,
    "text": "Car, s'ils tombent, l'un relève son compagnon; mais malheur à celui qui est seul et qui tombe, sans avoir un second pour le relever!",
    "translation": "LSG",
    "primary_emotion_tag": "loneliness",
    "secondary_tags": "community"
  },
  {
    "id": "igbo-ecclesiastes-4-10",
    "book": "Eklisiastis",
    "chapter": 4,
    "verse": 10,
    "text": "N'ihi na ọ buru na ha ada, otù nime ha gēme ka ibe-ya bilie: ma ahuhu gādiri onye ahu nke nání ya di mb͕e ọ nāda, ọ dighi kwa onye abua o nwere ime ka o bilie.",
    "translation": "IGBO",
    "primary_emotion_tag": "loneliness",
    "secondary_tags": "community"
  },
  {
    "id": "web-ephesians-4-26",
    "book": "Ephesians",
    "chapter": 4,
    "verse": 26,
    "text": "“Be angry, and don’t sin.” Don’t let the sun go down on your wrath,",
    "translation": "WEB",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "lsg-ephesians-4-26",
    "book": "Ephésiens",
    "chapter": 4,
    "verse": 26,
    "text": "Si vous vous mettez en colère, ne péchez point; que le soleil ne se couche pas sur votre colère,",
    "translation": "LSG",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "igbo-ephesians-4-26",
    "book": "Ndi Efesọs",
    "chapter": 4,
    "verse": 26,
    "text": "Unu emehiela mb͕e unu nēwe iwe: ekwela anyanwu da na nkpasu-iwe-unu:",
    "translation": "IGBO",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "web-james-1-19",
    "book": "James",
    "chapter": 1,
    "verse": 19,
    "text": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "translation": "WEB",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "lsg-james-1-19",
    "book": "Jacques",
    "chapter": 1,
    "verse": 19,
    "text": "Sachez-le, mes frères bien-aimés. Ainsi, que tout homme soit prompt à écouter, lent à parler, lent à se mettre en colère;",
    "translation": "LSG",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "igbo-james-1-19",
    "book": "Jemes",
    "chapter": 1,
    "verse": 19,
    "text": "Unu matara nka, umu-nnam ndi m'huru n'anya. Ma ka madu ọ bula buru onye nānu ihe ọsọsọ, onye nādighi ngwa ikwu okwu, nādighi kwa ngwa iwe iwe:",
    "translation": "IGBO",
    "primary_emotion_tag": "anger",
    "secondary_tags": ""
  },
  {
    "id": "web-proverbs-3-5",
    "book": "Proverbs",
    "chapter": 3,
    "verse": 5,
    "text": "Trust in Yahweh with all your heart, and don’t lean on your own understanding.",
    "translation": "WEB",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "trust"
  },
  {
    "id": "lsg-proverbs-3-5",
    "book": "Proverbes",
    "chapter": 3,
    "verse": 5,
    "text": "Confie-toi en l'Éternel de tout ton coeur, Et ne t'appuie pas sur ta sagesse;",
    "translation": "LSG",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "trust"
  },
  {
    "id": "igbo-proverbs-3-5",
    "book": "Ilu",
    "chapter": 3,
    "verse": 5,
    "text": "Tukwasi Jehova obi-gi nile, Adabere-kwa-la nghọta-gi:",
    "translation": "IGBO",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "trust"
  },
  {
    "id": "wlc-proverbs-3-5",
    "book": "משלי",
    "chapter": 3,
    "verse": 5,
    "text": "בְּטַח אֶל־יְהוָה בְּכָל־לִבֶּךָ וְאֶל־בִּינָתְךָ אַל־תִּשָּׁעֵן׃",
    "translation": "WLC",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "trust"
  },
  {
    "id": "web-psalms-139-23",
    "book": "Psalms",
    "chapter": 139,
    "verse": 23,
    "text": "Search me, God, and know my heart. Try me, and know my thoughts.",
    "translation": "WEB",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "self_examination"
  },
  {
    "id": "lsg-psalms-139-23",
    "book": "Psaumes",
    "chapter": 139,
    "verse": 23,
    "text": "Sonde-moi, ô Dieu, et connais mon coeur! Éprouve-moi, et connais mes pensées!",
    "translation": "LSG",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "self_examination"
  },
  {
    "id": "igbo-psalms-139-23",
    "book": "Abù Ọma",
    "chapter": 139,
    "verse": 23,
    "text": "Gwuputa ala obim, Chineke, we mara obim: Nānwam, we mara iche-uchem nile:",
    "translation": "IGBO",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "self_examination"
  },
  {
    "id": "wlc-psalms-139-23",
    "book": "תהלים",
    "chapter": 139,
    "verse": 23,
    "text": "חָקְרֵנִי אֵל וְדַע לְבָבִי בְּחָנֵנִי וְדַע שַׂרְעַפָּי׃",
    "translation": "WLC",
    "primary_emotion_tag": "confusion",
    "secondary_tags": "self_examination"
  },
  {
    "id": "web-ephesians-5-18",
    "book": "Ephesians",
    "chapter": 5,
    "verse": 18,
    "text": "Don’t be drunken with wine, in which is dissipation, but be filled with the Spirit,",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "lsg-ephesians-5-18",
    "book": "Ephésiens",
    "chapter": 5,
    "verse": 18,
    "text": "Ne vous enivrez pas de vin: c'est de la débauche. Soyez, au contraire, remplis de l'Esprit;",
    "translation": "LSG",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "igbo-ephesians-5-18",
    "book": "Ndi Efesọs",
    "chapter": 5,
    "verse": 18,
    "text": "Unu aṅubiga-kwa-la manya ókè, nke ndu ila-n'iyì di nime ya, kama juputanu na Mọ Nsọ;",
    "translation": "IGBO",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "web-proverbs-20-1",
    "book": "Proverbs",
    "chapter": 20,
    "verse": 1,
    "text": "Wine is a mocker and beer is a brawler. Whoever is led astray by them is not wise.",
    "translation": "WEB",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "lsg-proverbs-20-1",
    "book": "Proverbes",
    "chapter": 20,
    "verse": 1,
    "text": "Le vin est moqueur, les boissons fortes sont tumultueuses; Quiconque en fait excès n'est pas sage.",
    "translation": "LSG",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "igbo-proverbs-20-1",
    "book": "Ilu",
    "chapter": 20,
    "verse": 1,
    "text": "Onye nākwa emò ka manya-vine bu, onye-nkpọtu ka ihe-ọṅuṅu nke nābà n'anya bu; Onye ọ bula nke nāwaghari site na ya amaghi ihe.",
    "translation": "IGBO",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "wlc-proverbs-20-1",
    "book": "משלי",
    "chapter": 20,
    "verse": 1,
    "text": "לֵץ הַיַּין הֹמֶה שֵׁכָר וְכָל־שֹׁגֶה בּוֹ לֹא יֶחְכָּם׃",
    "translation": "WLC",
    "primary_emotion_tag": "craving",
    "secondary_tags": "alcohol"
  },
  {
    "id": "web-1corinthians-6-12",
    "book": "1 Corinthians",
    "chapter": 6,
    "verse": 12,
    "text": "“All things are lawful for me,” but not all things are expedient. “All things are lawful for me,” but I will not be brought under the power of anything.",
    "translation": "WEB",
    "primary_emotion_tag": "habit",
    "secondary_tags": "digital,behavioral"
  },
  {
    "id": "lsg-1corinthians-6-12",
    "book": "1 Corinthiens",
    "chapter": 6,
    "verse": 12,
    "text": "Tout m'est permis, mais tout n'est pas utile; tout m'est permis, mais je ne me laisserai asservir par quoi que ce soit.",
    "translation": "LSG",
    "primary_emotion_tag": "habit",
    "secondary_tags": "digital,behavioral"
  },
  {
    "id": "igbo-1corinthians-6-12",
    "book": "I. Ndi Kọrint",
    "chapter": 6,
    "verse": 12,
    "text": "Ihe nile zirim ezi n'iwu; ma ọ bughi ihe nile nābaram urù. Ihe nile zirim ezi n'iwu; ma ọ dighi ihe ọ bula gāchi mu onwem.",
    "translation": "IGBO",
    "primary_emotion_tag": "habit",
    "secondary_tags": "digital,behavioral"
  },
  {
    "id": "web-psalms-101-3",
    "book": "Psalms",
    "chapter": 101,
    "verse": 3,
    "text": "I will set no vile thing before my eyes. I hate the deeds of faithless men. They will not cling to me.",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "digital,pornography"
  },
  {
    "id": "lsg-psalms-101-3",
    "book": "Psaumes",
    "chapter": 101,
    "verse": 3,
    "text": "Je ne mettrai rien de mauvais devant mes yeux; Je hais la conduite des pécheurs; Elle ne s'attachera point à moi.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "digital,pornography"
  },
  {
    "id": "igbo-psalms-101-3",
    "book": "Abù Ọma",
    "chapter": 101,
    "verse": 3,
    "text": "M'gaghi-edo ihe jọb͕uru onwe-ya n'irum: Akpọwom ọlu nke ndi nējehie asì; Ọ gaghi- arapra n'arum.",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "digital,pornography"
  },
  {
    "id": "wlc-psalms-101-3",
    "book": "תהלים",
    "chapter": 101,
    "verse": 3,
    "text": "לֹא־אָשִׁית׀ לְנֶגֶד עֵינַי דְּבַר־בְּלִיָּעַל עֲשֹׂה־סֵטִים שָׂנֵאתִי לֹא יִדְבַּק בִּי׃",
    "translation": "WLC",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "digital,pornography"
  },
  {
    "id": "web-job-31-1",
    "book": "Job",
    "chapter": 31,
    "verse": 1,
    "text": "“I made a covenant with my eyes, how then should I look lustfully at a young woman?",
    "translation": "WEB",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "pornography"
  },
  {
    "id": "lsg-job-31-1",
    "book": "Job",
    "chapter": 31,
    "verse": 1,
    "text": "J'avais fait un pacte avec mes yeux, Et je n'aurais pas arrêté mes regards sur une vierge.",
    "translation": "LSG",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "pornography"
  },
  {
    "id": "igbo-job-31-1",
    "book": "Job",
    "chapter": 31,
    "verse": 1,
    "text": "Mu na anyam abua b͕ara ndu; M'gēsi kwa aṅa lekwasi nwa-ab͕ọghọ nāmaghi nwoke anya?",
    "translation": "IGBO",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "pornography"
  },
  {
    "id": "wlc-job-31-1",
    "book": "איוב",
    "chapter": 31,
    "verse": 1,
    "text": "בְּרִית כָּרַתִּי לְעֵינָי וּמָה אֶתְבּוֹנֵן עַל־בְּתוּלָה׃",
    "translation": "WLC",
    "primary_emotion_tag": "temptation",
    "secondary_tags": "pornography"
  }
];
