// Every word the interface shows, in one place.
// Written with .claude/skills/copywriting and edited with copy-editing's Seven Sweeps,
// following the voice guide in .agents/product-marketing.md. Translate by copying this file.

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const copy = {
  greeting(hour: number) {
    if (hour < 5) return 'Up late. You’re not alone';
    if (hour < 12) return 'Good morning';
    if (hour < 17) return 'Good afternoon';
    return 'Good evening';
  },

  welcome: {
    slides: [
      {
        title: 'Just today.',
        body: 'Not forever. Not perfect. Just today. Whatever pulls at you (a drink, a screen, a bet, a habit), you face it here with someone in your corner.',
      },
      {
        title: 'A slip never takes your light.',
        body: 'Every check-in, every urge you ride out, even every honest slip earns rays of light. A slip restarts a count. The light stays yours.',
      },
      {
        title: 'Yours alone.',
        body: 'No sign-up, no ads, no tracking. What you log stays on this phone. Free for good, and the code is open for anyone to check.',
      },
    ],
    next: 'Next',
    skip: 'Skip',
    begin: 'Start my first day',
    unsure: 'Not sure it’s a problem? You can just watch how often it happens. No pressure.',
  },

  newTracker: {
    back: '‹ Back',
    title: 'What pulls at you?',
    subtitle: 'Pick one or name it yourself. Anything counts, and you can add more later.',
    customLabel: 'Or name it yourself',
    customPlaceholder: 'e.g. energy drinks, online arguments',
    symbol: 'Pick a symbol',
    kind: 'What kind is it?',
    kinds: { substance: 'Something I take', behavioral: 'Something I do', digital: 'Something on a screen' },
    goalTitle: 'What do you want?',
    goalQuit: 'Stop completely',
    goalObserve: 'Just see how often',
    goalObserveBody: 'No counting, no pressure. Log it when it happens and we’ll show you the pattern. Switch to stopping whenever you’re ready.',
    goalQuitBody: 'We’ll count every day you stay free and mark each milestone with you.',
    intervalLabel: 'Big milestone every',
    intervalBody: 'Each big milestone banks 24 hours of “break time”. Most people find they never want to spend it. That’s the point: it’s proof you don’t need it.',
    toleranceNote: ' If you ever do, remember your body now handles far less than it used to. The old amount can be dangerous.',
    costTitle: 'What does it cost you?',
    costBody: 'Optional. We’ll show you what you win back.',
    money: 'Money a week',
    hours: 'Hours a week',
    whyTitle: 'Why do you want this?',
    whyBody: 'Optional. When it gets hard, we’ll show you these.',
    reason: (i: number) => `Reason ${i + 1}`,
    reasonHints: ['For my kids', 'To wake up clear-headed', 'To trust myself again'],
    startQuit: 'Start counting',
    startObserve: 'Start watching',
    privacy: 'Stays on this phone. Nothing is uploaded.',
  },

  home: {
    rays: (n: number) => `${n} rays`,
    toNext: (n: number, name: string) => `${n} rays to ${name}`,
    struggle: 'I’m struggling right now',
    checkIn: 'Check in for today',
    checkedIn: 'You checked in today. One more day.',
    milestone: (day: number, name: string) => `${day} days without ${name}.`,
    milestoneBody: 'That’s real, and it’s yours. Your light just grew.',
    addTracker: 'Track something else',
    wordToday: 'Word for today',
  },

  tracker: {
    details: 'Details ›',
    daysFree: (n: number) => (n === 1 ? 'day free' : 'days free'),
    toMilestone: (days: number, goal: number) => `${plural(days, 'day', 'days')} to your ${goal}-day milestone`,
    observeCount: 'times in the last 7 days · just watching',
    observeAxis: '4 weeks ago → this week',
    saved: 'saved',
    hoursBack: 'hours back',
    bestRun: 'best run',
    gentle: (goal: number) =>
      `The last two weeks have been hard. That’s okay. Forget the big number and aim for ${goal === 1 ? 'today' : `${goal} days`}. We’re right here.`,
    beatUrge: 'I rode it out',
    skipped: 'I skipped it',
    slipped: 'I slipped',
    didIt: 'It happened',
  },

  checkin: {
    back: '‹ Back',
    title: 'How’s the weather inside?',
    subtitle: 'No right answer. Just honest.',
    moods: ['Stormy', 'Rainy', 'Mixed', 'Bright', 'Sunny'],
    gratitude: 'One good thing today (optional)',
    gratitudeHint: 'Even a small one counts',
    note: 'Anything on your mind? (optional)',
    noteHint: 'Only you will see this.',
    anything: 'Did anything happen today?',
    hadSlip: 'I slipped',
    hadUrge: 'I had an urge',
    submit: 'Check in',
    done: (rays: number) => (rays > 0 ? `+${rays} rays` : 'You checked in'),
    back2: 'Back to today',
  },

  struggle: {
    back: '‹ Back',
    title: 'You reached out. That’s the hardest part.',
    body: 'An urge rises, peaks, and falls, like a wave. Let’s ride this one together. Breathe with the circle.',
    breaths: (n: number) => `${Math.min(n, 3)} of 3 breaths`,
    calmer: 'I’m a little calmer',
    skip: 'Skip ahead',
    toolsTitle: 'The next 15 minutes',
    toolsBody: 'Pick one thing and do it now. Then come back and tell me how it went.',
    rememberWhy: 'Remember why',
    tryOne: 'Try one of these',
    hobby: (h: string) => `Do something you love: ${h}. Even 10 minutes.`,
    talk: 'Talk it through',
    howDidItGo: 'How did it go?',
    whichOne: 'Which one was it?',
    rodeItOut: 'I rode it out',
    gaveIn: 'I gave in',
    wonTitle: 'You rode it out.',
    back2: 'Back to today',
  },

  slip: {
    back: '‹ Back',
    title: 'It happened. You’re still here.',
    titleObserve: 'Log it',
    body: 'Telling the truth right now takes courage. Let’s look at what happened, then take the next right step.',
    bodyObserve: 'Just the facts. Each one makes your pattern clearer.',
    which: 'Which one?',
    when: 'When?',
    whenOptions: { now: 'Just now', earlier: 'Earlier today', yesterday: 'Yesterday' },
    feeling: 'What were you feeling?',
    note: 'What happened? (optional, only you see this)',
    submit: 'Log it honestly',
    doneTitle: 'Thank you for telling the truth.',
    doneTitleObserve: 'Logged. Thank you.',
    doneBody: 'A slip doesn’t erase the days you fought for. Today is day 0, and day 0 is still a day in the fight.',
    doneBodyObserve: 'Every log makes your pattern clearer. No judgement here.',
    stillHave: 'What you still have',
    bestRun: (n: number) => `Your best run is ${n} days. You’ve done it before. You can do it again.`,
    honesty: (n: number) => `+${n} rays for honesty.`,
    talk: 'Talk about what happened',
    home: 'Back to today',
  },

  guide: {
    title: 'A word for right now',
    searching: ['Reading the scriptures for you…', 'Looking for the right passage…', 'Choosing carefully…'],
    why: 'Why this passage',
    sitWith: 'Sit with this',
    pray: 'Pray',
    readToday: (ch: string) => `Read ${ch} today`,
    nextStep: 'Next hour',
    another: 'Another passage',
    offline: 'You’re offline, so this verse comes from the ones saved on your phone.',
  },

  sponsor: {
    back: '‹ Back',
    title: 'Talk',
    private: 'Private · not saved',
    placeholder: 'Say what’s going on…',
    send: 'Send',
    remember: 'Remember this about you for next time?',
    yes: 'Yes, remember',
    no: 'No thanks',
  },

  journey: {
    title: 'Your journey',
    rays: (n: number) => `${n} rays of light, earned and kept.`,
    levels: 'From night to sunshine',
    youAreHere: '· you are here',
    last14: 'Last 14 days',
    weather: 'The weather you checked in with.',
    fighting: 'What you’re facing',
    thisWeek: (n: number) => `${n} this week`,
    streak: (now: number, best: number) => `${now}d · best ${best}d`,
    patterns: 'When it gets hard',
    patternsBody: 'These are the times it tends to pull hardest. We’ll try to check in before them.',
    patternsEmpty: 'After a few logs, you’ll see when urges tend to hit, so you can plan ahead.',
    recent: 'Recent light',
    rayLabels: {
      first_step: 'Took the first step',
      checkin: 'Checked in',
      urge_beaten: 'Rode out an urge',
      honest_slip: 'Told the truth about a slip',
      reflection: 'Talked it through',
      milestone: 'Reached a milestone',
    } as Record<string, string>,
  },

  settings: {
    title: 'Settings',
    subtitle: 'Everything here stays on this phone.',
    bibleTitle: 'Bible language',
    bibleBody: 'The Scripture Guide will choose passages and pray with you in this language.',
    bibleNote: 'Hebrew covers the Old Testament. New Testament passages show in English.',
    reminderTitle: 'Daily reminder',
    reminderBody: 'Adds one repeating check-in to your Google Calendar. We never sign in to your Google account. You just tap Save.',
    remindAt: 'Remind me at',
    addCalendar: 'Add to Google Calendar',
    aboutTitle: 'About me',
    aboutBody: 'Optional. Helps your sponsor and the Scripture Guide suggest things that fit your life. Sent to the AI only when you use it, never with your name.',
    save: 'Save',
    saved: 'Saved. Your sponsor will use this for better ideas.',
    backupTitle: 'Backup and new phone',
    backupBody: 'Free, always. Download one file with everything, then open it on your new phone or browser. No account needed.',
    download: 'Download my backup',
    restore: 'Restore from a backup',
    backupReady: 'Backup ready. Keep it somewhere safe. It holds your private history.',
    restored: 'Restored. Welcome back.',
    unreadable: 'That file couldn’t be read.',
    openTitle: 'Open source and privacy',
    openBody: 'No accounts, no ads, no trackers. When you talk to your sponsor or the Scripture Guide, only that request goes to the AI, and our server keeps nothing.',
    viewCode: 'Read the code and docs ›',
    legal: 'Not medical care. Scripture: World English Bible, Louis Segond 1910, Bible Nsọ (Igbo), Westminster Leningrad Codex, all public domain. License: AGPL-3.0.',
    deleteTitle: 'Delete everything',
    deleteBody: 'Removes all your data from this phone.',
    deleteConfirmBody: 'This can’t be undone. Every tracker, log, check-in and ray will be gone. Download a backup first if you might want it.',
    deleteButton: 'Delete all my data',
    deleteConfirm: 'Yes, delete everything',
    cancel: 'Cancel',
  },

  levelUp: {
    kicker: 'New light',
    tap: 'Tap to keep going',
  },

  nav: { today: 'Today', journey: 'Journey', talk: 'Talk', settings: 'Settings' },
} as const;
